# build stage
FROM registry.blocksource.nl/pooldetective-vnext-base AS build-env
RUN mkdir -p /go/src/github.com/mit-dci/pooldetective/
ADD . /go/src/github.com/mit-dci/pooldetective/
WORKDIR /go/src/github.com/mit-dci/pooldetective/reorgtracker
RUN go get ./...
RUN go build -o reorgtracker

# final stage
FROM alpine
RUN apk --no-cache add ca-certificates libzmq
WORKDIR /app
COPY --from=build-env /go/src/github.com/mit-dci/pooldetective/reorgtracker/reorgtracker /app/
ENTRYPOINT ./reorgtracker