# build stage
FROM registry.blocksource.nl/pooldetective-vnext-base AS build-env
RUN mkdir -p /go/src/github.com/mit-dci/pooldetective/
ADD . /go/src/github.com/mit-dci/pooldetective/
WORKDIR /go/src/github.com/mit-dci/pooldetective/blockfetcher
RUN go get ./...
RUN go build -o blockfetcher

# final stage
FROM alpine
RUN apk --no-cache add ca-certificates libzmq
WORKDIR /app
COPY --from=build-env /go/src/github.com/mit-dci/pooldetective/blockfetcher/blockfetcher /app/
ENTRYPOINT ./blockfetcher