# build stage
FROM pooldetective-base AS build-env
RUN mkdir -p /go/src/github.com/mit-dci/pooldetective/
ADD . /go/src/github.com/mit-dci/pooldetective/
WORKDIR /go/src/github.com/mit-dci/pooldetective/dbqueries
RUN go get ./...
RUN go build -o dbqueries

# final stage
FROM alpine
RUN apk --no-cache add ca-certificates libzmq
WORKDIR /app
COPY --from=build-env /go/src/github.com/mit-dci/pooldetective/dbqueries/dbqueries /app/
ENTRYPOINT ./dbqueries
